---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.1.0

jobs:
  test:
    docker:
    - image: circleci/golang:1.12

    steps:
    - prometheus/setup_environment
    - setup_remote_docker
    - run: make
    - prometheus/store_artifact:
        file: aws_billing_exporter

workflows:
  version: 2
  aws_billing_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: abcdevops
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: abcdevops
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
